package com.rayyan.finance_tracker.entity.authentication;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class AuthenticationRequest {
    private String username; // email can be used as username
    private String password;

    // Getters and Setters are generated by Lombok
}
