# This name will appear in the "Actions" tab of your GitHub repository.
name: Java CI Pipeline (Test and Build)

# THIS IS THE FIX: Run on every push to the 'main' branch
on:
  push:
    branches:
      - "master"
      - "broken-code"

  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven Packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build and Test with Maven
        run: mvn -B clean install